apiVersion: v1
kind: Service
metadata:
  namespace: presensi
  name: nginx-presensi
  labels:
    run: nginx-presensi
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP
  selector:
    run: nginx-presensi
