kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: presensi
  name: presensi-pv-volume
  labels:
    type: local
    app: presensi
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: presensi
  name: presensi-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi