apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: presensi
  name: nginx-presensi
spec:
  selector:
    matchLabels:
      run: nginx-presensi
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-presensi
    spec:
      containers:
      - name: nginx-presensi
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: presensi-pv-storage
            mountPath: /var/www/html
          - name: presensi-nginx-config
            mountPath: /etc/nginx/conf.d

      volumes:
        - name: presensi-pv-storage
          emptyDir: {}
          #persistentVolumeClaim:
          #  claimName: presensi-pv-claim
        - name: presensi-nginx-config
          configMap:
            name: presensi-nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: presensi
  name: phpfpm-presensi
spec:
  selector:
    matchLabels:
      run: phpfpm-presensi
  replicas: 1
  template:
    metadata:
      labels:
        run: phpfpm-presensi
    spec:
      #initContainers:
      containers:
#      - name: git-clone
#        image: alpine/git # Any image with git will do
#        command:
#          - /usr/local/git/git-clone.sh
#        args:
#          - "https://github.com/mrcoco/slim3-eloquent-skeleton.git"
#          - "/app"
#        #envFrom:
#        #  - secretRef:
#        #      name: git-secret
#        volumeMounts:
#          - name: git-clone
#            mountPath: /usr/local/git
#          - name: git-repo
#            mountPath: /app
      #containers:
      - name: phpfpm-presensi
        image: dwiagus/phalcon:01
        ports:
          - containerPort: 9000
        #command:
        #  - /usr/local/composer/composer-update.sh
        #args:
        #  - "/var/www/html/app"
#        volumeMounts:
#          - name: presensi-pv-storage
#            mountPath: /var/www/html
          #- name: git-repo
          #  mountPath: /var/app
          #- name: composer-update
          #  mountPath: /usr/local/composer

      volumes:
#        - name: git-repo
#          emptyDir: {}
#        - name: git-clone
#          configMap:
#            name: git-clone
#            defaultMode: 0755
#        - name: composer-update
#          configMap:
#            name: composer-update
#            defaultMode: 0755
        - name: presensi-pv-storage
          emptyDir: {}
          #persistentVolumeClaim:
          #  claimName: presensi-pv-claim