apiVersion: v1
kind: Service
metadata:
  namespace: presensi
  name: phpfpm-presensi
  labels:
    run: phpfpm-presensi
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30002
      protocol: TCP
  selector:
    run: phpfpm-presensi