apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
              name: presensidb
          volumeMounts:
            - name: presensi-pv-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: presensi-pv-data
          persistentVolumeClaim:
            claimName: postgres-presensi-pv-claim