apiVersion: v1
kind: Service
metadata:
  namespace: presensi
  name: mongo
  labels:
    role: mongo
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo